#!/bin/sh

#
# you must set WORKDIR, $abi, $package_set, and $url_package_set before invoking this script.
# $package_set is one of latest/quartery/kmod. $url_package_set adjusts kmod to
# kmods_latest_2 which is what the server uses on disk.
#
# this script is invoked by fetch-extract-parse-import-one-abi.sh
# this scripts sets ARCHIVE_FILE and PACKAGE_FILE as return vars for that script
#
# At one time, this script set three values... but here we are.
#

# get the name of this script
LOGGERTAG=${0##*/}


# we just try to create every time
WORKDIR="$BASEDIR_PACKAGER/$abi/$package_set"
$LOGGER -t $LOGGERTAG creating $WORKDIR
mkdir -p $WORKDIR

if [ ! -d $BASEDIR_PACKAGER ]
then
  $LOGGER -t $LOGGERTAG "FATAL error: $BASEDIR_PACKAGER does not exist - $0 terminating"
  exit 1
fi

if [ ! -d $WORKDIR ]
then
  mkdir -p $WORKDIR
  if [ $? -ne 0 ]
  then
    $LOGGER -t $LOGGERTAG "FATAL error: unable to create $WORKDIR - $0 terminating"
    exit 1
  fi  
fi

$LOGGER -t $LOGGERTAG cd $WORKDIR/
cd $WORKDIR/

# now we fetch meta.conf
#
METAFILE=$(mktemp $WORKDIR/meta.conf.XXXXXX)
$LOGGER -t $LOGGERTAG fetch --quiet --output=$METAFILE https://pkg.freebsd.org/$abi/$url_package_set/meta.conf

# NOTE: some older ABI do not have meta.conf
# Notably
# * FreeBSD:12:aarch64 latest, 
# * FreeBSD:12:armv6 latest
# * FreeBSD:12:armv7
#
# If not found, we assumes it is older, and use older default values.
#

# based on https://github.com/freebsd/pkg/blob/main/NEWS#L274 (use data.pkg instead of packagesite.pkg if available)
# start using data.pkg if available

# redirect stderr to /dev/null so it does not appear in the logs
fetch --quiet --output=$METAFILE https://pkg.freebsd.org/$abi/$url_package_set/meta.conf 2>/dev/null
if [ $? -ne 0 ]
then
  $LOGGER -t $LOGGERTAG "WARNING: unable to fetch https://pkg.freebsd.org/$abi/$url_package_set/meta.conf - using default values."
  ARCHIVE_FILE=packagesite.txz
  PACKAGE_FILE=packagesite.yaml
else
  $LOGGER -t $LOGGERTAG "at one time, we parsed the fetched meta.conf file for pkg archive details. Now it's hardcoded."

  # This is the name of the file we pull down from the server
  ARCHIVE_FILE="data.pkg"

  # the name of the file was obtained from $METAFILE - look for manifests - at present, that is broken. Seems hardcoded to packagesite.yaml
  PACKAGE_FILE="data"
fi

# disable for now

rm -f $METAFILE
